server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./db/testDatabase
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

  h2:
    console:
      enabled: true
